name: lamob_dart_extensions
repository: https://github.com/LaMobilery/oss_dart_extensions

packages:
  - packages/**

scripts:
  create_extensions:
    name: create_extensions
    description: Create a new package for extensions for the class given as argument
    run: dart bin/create_extensions.dart
      